version: '3'
services:
  selenium:
    image: selenium/standalone-firefox:3.141.59-20200826
    ports:
      - 4444:4444
  app:
    build: .
    command: python scrapper_code.py
    volumes:
      - .:/codewars
    links:
      - selenium