name: Automatizar el archivo

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Docker containers
      uses: docker/compose-action@v1
      with:
        command: up -d
        compose-file: docker-compose.yml
        working-directory: .
        env:
          ENV_VAR: value