name: Automatizar el archivo

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Run the script
      run: |
        python scrapper_code.py

    - name: Commit and push changes
      uses: endormi/action-auto-commit-push@v0
      with:
        commit_message: Automated update
        push_branch: main
